language: node_js
node_js:
  - "lts/*"
cache: npm
script:
  - npm run lint
  - npm run test -- --coverage
  - npm run build
after_success:
 - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app: ominidi-pwa
  skip_cleanup: true
  api_key:
    secure: $HEROKU_API_KEY
